language: c
dist: trusty
install:
    - ./.travis/install_compiler.sh
    - ./install-dependencies.sh
    - sudo usermod -a -G audio travis
    - sudo modprobe snd-aloop index=1 pcm_substreams=1
    - cd $TRAVIS_BUILD_DIR && cp ./.travis/.asoundrc ~/.asoundrc
    - sudo alsa force-reload
script:
    - cd $TRAVIS_BUILD_DIR && ./bootstrap
    - cd build && make check CTEST_OUTPUT_ON_FAILURE=TRUE
    - make programs && sudo make install
    - cd ..
    - sg audio -c "quiet_decode_soundcard audible README.md.soundcard &"
    - sg audio -c "quiet_encode_soundcard audible README.md"
    - sleep 6
    - killall quiet_decode_soundcard
    - sleep 1
    - quiet_encode_file audible README.md
    - quiet_decode_file audible README.md.file
    - diff --from-file=README.md README.md.soundcard README.md.file
